"""MongoDB repository classes for MDIP operational collections."""

from app.repositories.collections import (
    COLLECTION_REPOSITORIES,
    AgentMemoryRepository,
    DecisionHistoryRepository,
    DemandSignalsRepository,
    GraphEdgesRepository,
    GraphNodesRepository,
    HistoricalIncidentsRepository,
    InventoryRepository,
    LogisticsPartnersRepository,
    PlantsRepository,
    PlaybooksRepository,
    ProductsRepository,
    PromotionsRepository,
    RegionsRepository,
    RetailSalesRepository,
    ShipmentsRepository,
    SuppliersRepository,
    WarehousesRepository,
    WeatherEventsRepository,
)

__all__ = [
    "AgentMemoryRepository",
    "COLLECTION_REPOSITORIES",
    "DemandSignalsRepository",
    "DecisionHistoryRepository",
    "GraphEdgesRepository",
    "GraphNodesRepository",
    "HistoricalIncidentsRepository",
    "InventoryRepository",
    "LogisticsPartnersRepository",
    "PlantsRepository",
    "PlaybooksRepository",
    "ProductsRepository",
    "PromotionsRepository",
    "RegionsRepository",
    "RetailSalesRepository",
    "ShipmentsRepository",
    "SuppliersRepository",
    "WarehousesRepository",
    "WeatherEventsRepository",
]
